### ISSUE TITLE
Client can't connect to the service hosted inside nested iframe and that listens on parent window

### ISSUE THREAD

**Issue by azasypkin** [gaia-components/threads#83]
See demo at: http://nga-crash-tests.github.io/bridge-iframe-service/

See source at: https://github.com/nga-crash-tests/bridge-iframe-service

**Comment by wilsonpage** [comment]
Discussed offline. This is difficult as the parent window is attempting to connect to an iframe service that has not yet loaded. Adding support for this inside Bridge will add complexity with questionable value.

Options:
- A. Wait for iframe to load before attempting to `client.connect()` or calling `client.method()` or `client.on()`
- B. Keep manually calling `.connet()` until the iframe service is loaded and receives the connect requrest. This could be built as a Client plugin.
- C. Get a handle on the iframe and use standard syntax: `var client = bridge.client('my-service', iframe)`

**Comment by wilsonpage** [comment]
Please re-open if you feel this should be fixed inside bridge core :)

**Comment by azasypkin** [comment]
> C. Get a handle on the iframe and use standard syntax: var client = bridge.client('my-service', iframe)

Seems we'll have the same problem with this approach if iframe hasn't created service yet. If I'm not mistaken little-browser uses exactly the same approach - it's supposed to create iframe with bridge service inside which client is inside top window :/ @wilsonpage would it work if we use `postMessage` instead of `dispatchEvent`? If so is it possible to allow bridge consumer to configure this behavior with something like `sync: false` option that will use `postMessage` instead?

In the meantime will try A and B that you proposed above.

**Comment by wilsonpage** [comment]
Bridge.js will attempt to connect as soon as the iframe has loaded. It will not wait until after that point. This means that you need to create your service ASAP inside the iframe. Not async.

> @wilsonpage would it work if we use postMessage instead of dispatchEvent? If so is it possible to allow bridge consumer to configure this behavior with something like sync: false option that will use postMessage instead?

There is a chance due to the async nature of postMessage that this would extend the period of time in which you can get your service started, although this sounds racy. I think we should have the option to opt-in to `sync` messaging and default to normal postMessage. I don't have the time right now to build this feature though.
